volumes:
  data:

services:
  database:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

